//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RWFile.LocalDB
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class BIN_REACHED
    {
        
        public string Bin_Reached_ID { get; set; } 
        public decimal X { get; set; } 
        public decimal Y { get; set; } 
        public int DUT { get; set; } 
        public string Result { get; set; } 
        public int bin1 { get; set; } 
        public int bin2 { get; set; } 
        public string FK_WT_ID { get; set; }
    }
}
