//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RWFile.LocalDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Power
    {
        public string Power_ID { get; set; }
        public string Pin_name { get; set; }
        public string mA { get; set; }
        public string FK_WT_ID { get; set; }
    }
}
